# Generated by Django 4.1.7 on 2023-03-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_rename_news_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='events',
            name='updated_at',
        ),
    ]
