# Generated by Django 4.1.7 on 2023-03-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_remove_events_created_at_remove_events_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='link',
            field=models.CharField(max_length=2083),
        ),
    ]
