# Generated by Django 4.1.7 on 2023-03-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0005_rename_name_events_eventname_remove_events_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
